name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Social Media CLI are you running?
      placeholder: ex. 1.0.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Social Media Platform
      description: Which platform(s) are affected?
      multiple: true
      options:
        - Facebook
        - Instagram
        - Telegram
        - LinkedIn
        - All platforms
        - Not platform-specific
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Your operating system and Node.js version
      placeholder: ex. macOS 13.0, Node.js 18.17.0
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Run command '...'
        2. Enter input '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Share your configuration (remove any sensitive information like API keys)
      render: json

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
